### ISSUE TITLE
There was some problem registering you! Please try again later! 

### ISSUE THREAD

**Issue by suthargk** [neverwannafly/PlayChess#15]
There was some problem registering you! Please try again later!

**Comment by neverwannafly** [comment]
Can you please elaborate?
It would be awesome if you could tell me what exactly you did to face this problem?

**Comment by suthargk** [comment]
I can't register

**Comment by neverwannafly** [comment]
Do you have team viewer?

**Comment by neverwannafly** [comment]
I just saw this issue on Heroku deployment. 
I'll do my best to fix it immediately!

**Comment by neverwannafly** [comment]
Fixed 7be67d4701cac33c1e9ea060f72c6a32d93caed4
